name: Request airdrop

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"
  push:

jobs:
  request-airdrop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        run: |
          yarn
          yarn node airdrop
